# Exode.biz Multi-Service Makefile

.PHONY: up down logs ps restart

up:
	docker-compose up --build -d

down:
	docker-compose down

logs:
	docker-compose logs -f

ps:
	docker-compose ps

restart:
	docker-compose restart
