ALTER TABLE users ADD COLUMN IF NOT EXISTS level VARCHAR(20) NOT NULL DEFAULT 'junior';
ALTER TABLE enrollments ADD COLUMN IF NOT EXISTS source VARCHAR(20) NOT NULL DEFAULT 'self';
ALTER TABLE enrollments ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT NOW();
